package btl_jv;

//import btl_jv.Admin;
//import btl_jv.DBEngine;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author NTHT
 */
public class QLySinhVien extends javax.swing.JFrame {

    /**
     * Creates new form QLySinhVien
     */
    
    ArrayList<Sinhvien> dssv=new ArrayList<>();
    
    Sinhvien sv=new Sinhvien();
    DBEngine doc = new DBEngine();
    String file = "Quan_Ly_sinh_vien.txt";
    File fileName = new File("SinhVien_Excel.xls");
    int chon = -1;
    void cbxDocNganh(){
        String nganh [] ={"Hệ thống thông tin","Kỹ thuật phần mềm","Công nghệ thông tin","Khoa học máy tính"};
        cbxNganh.setModel(new DefaultComboBoxModel<>(nganh));
    }
    
    void cbxCSTT(){
        String cstt []={"Công Ty Cổ Phần Đào Tạo Quản Lý Trực Tuyến Omt",
                        "Công ty Cổ phần RikkeiSoft",
                        "Công ty TNHH phần mềm FPT",
                        "Công ty cổ phần Misa"};
        cbxCoSoTT.setModel(new DefaultComboBoxModel<>(cstt));
    }
    
    public QLySinhVien() {
        initComponents();
        setLocationRelativeTo(null);
        fakeData();
        cbxDocNganh();
        cbxCSTT();
        //docFile();
        loadTableSV();
    }

    public void fakeData(){
        Sinhvien sv1=new Sinhvien("SV1", "Lê Tuấn Anh", "Vũ Thị Dương", "Đã thông qua", "Khoa học máy tính", "Công ty Cổ phần RikkeiSoft");
        dssv.add(sv1);
        Sinhvien sv2=new Sinhvien("SV2", "Ngô Mạnh Hùng", "Phạm Văn Hiệp", "Đang chờ", "Công nghệ thông tin", "Công ty TNHH phần mềm FPT");
        dssv.add(sv2);
        Sinhvien sv3=new Sinhvien("SV3", "Đỗ Huy Hoàng", "Hoàng Quang Huy", "Đang chờ", "Kỹ thuật phần mềm", "Công Ty Cổ Phần Đào Tạo Quản Lý Trực Tuyến Omt");
        dssv.add(sv3);
        Sinhvien sv4=new Sinhvien("SV4", "Nguyễn Thị Thủy", "Nguyễn Bá Nghiễn", "Đã thông qua", "Hệ thống thông tin", "Công Ty Cổ Phần Đào Tạo Quản Lý Trực Tuyến Omt");
        dssv.add(sv4);
        Sinhvien sv5=new Sinhvien("SV5", "Nguyễn Thị Huyền Trang", "Vũ Đình Minh", "Đã thông qua", "Hệ thống thông tin", "Công Ty Cổ Phần Công Nghệ Itg");
        dssv.add(sv5);
    }
    public void luuFile(){
        try {
            doc.luuFile(file, dssv);
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }
    
    public void docFile(){
        try {
            dssv = (ArrayList) doc.docFile(file);
        } catch (Exception e) {
            System.out.println("Có lỗi: "+e.toString());
        }
    }

    public void loadTableSV(){
        tblSinhVien.setModel(new TableSV(dssv));
        luuFile();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        btnDatLai = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXuatFile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSinhVien = new javax.swing.JTable();
        btnTimKiem = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableTim = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        txtGiaoVienHD = new javax.swing.JTextField();
        txtTrangThai = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbxCoSoTT = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbxNganh = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        trangchu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Quản lý sinh viên thực tập");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Nhập thông tin");

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnDatLai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDatLai.setText("Đặt lại");
        btnDatLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatLaiActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXuatFile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXuatFile.setText("Xuất file");
        btnXuatFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatFileActionPerformed(evt);
            }
        });

        tblSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã sinh viên", "Tên sinh viên", "Ngành", "Giáo viên HD", "Cơ sở thực tập", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSinhVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSinhVien);
        if (tblSinhVien.getColumnModel().getColumnCount() > 0) {
            tblSinhVien.getColumnModel().getColumn(0).setMinWidth(8);
            tblSinhVien.getColumnModel().getColumn(0).setPreferredWidth(8);
            tblSinhVien.getColumnModel().getColumn(5).setPreferredWidth(8);
        }

        btnTimKiem.setBackground(new java.awt.Color(153, 153, 255));
        btnTimKiem.setText("Search");
        btnTimKiem.setToolTipText("");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel6.setText("Tìm kiếm:");

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        tableTim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã sinh viên", "Tên sinh viên", "Ngành", "Giáo viên HD", "Cơ sở thực tập", "Trạng thái"
            }
        ));
        tableTim.setRowHeight(30);
        jScrollPane3.setViewportView(tableTim);
        if (tableTim.getColumnModel().getColumnCount() > 0) {
            tableTim.getColumnModel().getColumn(0).setPreferredWidth(15);
            tableTim.getColumnModel().getColumn(5).setPreferredWidth(8);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Tên:");

        jLabel4.setText("Giáo viên HD:");

        jLabel5.setText("Trạng thái:");

        jLabel7.setText("Mã sinh viên:");

        jLabel8.setText("Cơ sở thực tập:");

        cbxCoSoTT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxCoSoTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCoSoTTActionPerformed(evt);
            }
        });

        jLabel9.setText("Ngành:");

        cbxNganh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxNganh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNganhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTen, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(txtGiaoVienHD)
                    .addComponent(txtTrangThai))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxCoSoTT, 0, 228, Short.MAX_VALUE)
                    .addComponent(cbxNganh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaSV))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtGiaoVienHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxCoSoTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setText("+ Thêm");
        btnThem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Danh sách sinh viên thực tập:");

        trangchu.setText("Trang chủ");
        trangchu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trangchuMouseClicked(evt);
            }
        });
        jMenuBar1.add(trangchu);

        jMenu2.setText("Refresh");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btnThem)
                        .addGap(48, 48, 48)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnDatLai)
                        .addGap(56, 56, 56)
                        .addComponent(btnXuatFile)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(169, 169, 169))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiem)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addComponent(jLabel2)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXuatFile)
                    .addComponent(btnDatLai)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnThem))
                .addGap(29, 29, 29)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// bắt lỗi
    public JTextField gettxtMaSV() throws Exception{
        if(txtMaSV.getText().equals("")){
            throw  new Exception("Không được để trống mã sinh viên!");
        }
        if(dssv.contains(new Sinhvien(txtMaSV.getText().trim().toUpperCase()))){
            throw new Exception("Ma sinh vien da ton tai");
        }
        return txtMaSV;
    }
    
    public JTextField gettxtTen() throws Exception{
        if(txtTen.getText().equals("")){
            throw  new Exception("Không được để trống tên sinh viên!");
        }
        return txtTen;
    }
    public JTextField gettxtGVHD() throws Exception{
        if(txtGiaoVienHD.getText().equals("")){
            throw  new Exception("Khhông được để trống giáo viên hướng dẫn!");
        }
        return txtGiaoVienHD;
    }
    public JTextField gettxtTrangThai() throws Exception{
        if(txtTrangThai.getText().equals("")){
            throw  new Exception("Không được để trống trạng thái!");
        }
        return txtTrangThai;
    }
    public JTextField gettxtTimKiem() throws Exception{
        if(txtTimKiem.getText().equals("")){
            throw new Exception("Vui lòng nhập mã sinh viên cần tìm!");
        }
        return txtTimKiem;
    }
    
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try {
            
            sv=new Sinhvien(gettxtMaSV().getText(), gettxtTen().getText(), gettxtGVHD().getText(), 
                    gettxtTrangThai().getText(), cbxNganh.getSelectedItem().toString(), 
                    cbxCoSoTT.getSelectedItem().toString());
            if(!dssv.contains(sv)){
                dssv.add(sv);
                
                loadTableSV();
                JOptionPane.showMessageDialog(QLySinhVien.this, "Thêm sinh viên thành công", 
                        "", JOptionPane.INFORMATION_MESSAGE);
                
            }else{
                JOptionPane.showConfirmDialog(QLySinhVien.this, "Thông tin sinh viên đã tồn tại ", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(QLySinhVien.this, "Có lỗi: "+e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThemActionPerformed

   
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        try {
            int row=tblSinhVien.getSelectedRow();
            if(row==-1){
                JOptionPane.showMessageDialog(QLySinhVien.this, "Vui lòng chọn sinh viên muốn xóa", "Loi", JOptionPane.ERROR_MESSAGE);
            }else{
                int confirm=JOptionPane.showConfirmDialog(QLySinhVien.this, "Bạn có chắc chắn muốn xóa sinh viên này?", "Error", JOptionPane.YES_NO_OPTION);
                if(confirm == JOptionPane.YES_OPTION){
                    dssv.remove(row);
                    loadTableSV();
                    JOptionPane.showMessageDialog(QLySinhVien.this, "Xóa sinh viên thành công!", "", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Có lỗi: "+e.toString());
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnDatLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatLaiActionPerformed
        // TODO add your handling code here:
        txtMaSV.setText("");
        txtTen.setText("");
        cbxNganh.setSelectedItem(0);
        txtGiaoVienHD.setText("");
        cbxCoSoTT.setSelectedItem(0);
        txtTrangThai.setText("");
    }//GEN-LAST:event_btnDatLaiActionPerformed

    private void checkDong() throws Exception{
        if(chon==-1){
            throw  new Exception("Ban chua chon dong");
        }
    }
    
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        
            try {
                chon = tblSinhVien.getSelectedRow();
                checkDong();
                Sinhvien sps = new Sinhvien();
                if (dssv.get(chon).getMaSV().equalsIgnoreCase(txtMaSV.getText().trim())) {
                    sps.setMaSV(txtMaSV.getText().trim().toUpperCase() + "");
            }
                else{
                    sps.setMaSV(gettxtMaSV().getText().trim().toUpperCase() + "");
                }
                    sps.setTenSV(gettxtTen().getText().trim() + "");
                    sps.setGiaoVienHD(txtGiaoVienHD.getText().trim());
                    sps.setNganh(cbxNganh.getSelectedItem().toString());
                    sps.setCoSoTT(cbxCoSoTT.getSelectedItem().toString());
                    sps.setTrangThai(txtTrangThai.getText().trim());
                    dssv.set(chon, sps);
                    loadTableSV();
                    JOptionPane.showMessageDialog(QLySinhVien.this, "Sửa sinh viên thành công", "Thong bao", JOptionPane.INFORMATION_MESSAGE);
                    
            } catch (Exception e) {
                JOptionPane.showMessageDialog(QLySinhVien.this, e.toString(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }      
    }//GEN-LAST:event_btnSuaActionPerformed

    
    //lam viec voi file excel
    
    //tao 1 doi tuong cho excel
   Workbook workbook = new XSSFWorkbook(); 
    //tao 1 sheet
    Sheet sheet = (Sheet) workbook.createSheet("SinhVien");
    //Excel WBook = new XSSFWorkbook(ExcelFile);
    public void xuatFileExel(JTable table) throws IOException{
        //tao ten cot
        Row headerRow = sheet.createRow(0);
        for(int i=0 ; i<table.getColumnCount() ; i++){
            Cell headerCell = headerRow.createCell(i);
            headerCell.setCellValue(table.getColumnName(i));
            
            //tao font chữ đậm
            org.apache.poi.ss.usermodel.Font font=workbook.createFont();
            font.setBold(true);
            
            //tạo font chữ cho CellStyle
            CellStyle style = workbook.createCellStyle();
            style.setFont(font);
            
            //áp dụng CellStyle cho tên cột
            headerCell.setCellStyle(style);
        }
        //thêm dữ liệu tring jtable vào trong file
        for(int i=0 ; i<table.getRowCount() ; i++){
            Row row = sheet.createRow(i+1);
            for(int j=0 ; j<table.getColumnCount() ; j++){
                Cell cell = row.createCell(j);
                cell.setCellValue(table.getValueAt(i, j).toString());
            }
        }
        FileOutputStream fos = new FileOutputStream("Sinh_Vien.xlsx");
        workbook.write(fos);
        fos.close();
        JOptionPane.showMessageDialog(null, "da xuat file: Sinh_Vien.xlsx");
    }
    
    private void btnXuatFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatFileActionPerformed
        // TODO add your handling code here:
        try {
            xuatFileExel(tblSinhVien);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btnXuatFileActionPerformed

//hien thi thong tin sinh vien sau khi chon dong trong bang
    private void tblSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSinhVienMouseClicked
        // TODO add your handling code here:
        chon=tblSinhVien.getSelectedRow();
        if(chon != -1){
            
                sv=dssv.get(chon);
                txtMaSV.setText(sv.getMaSV()+"");
                txtTen.setText(sv.getTenSV()+"");
                cbxNganh.setSelectedItem(sv.getNganh());
                txtGiaoVienHD.setText(sv.getGiaoVienHD()+"");
                cbxCoSoTT.setSelectedItem(sv.getCoSoTT());
                txtTrangThai.setText(sv.getTrangThai()+"");
        }   
    }//GEN-LAST:event_tblSinhVienMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        ArrayList<Sinhvien> dstim = new ArrayList<>();
        try {
            for (Sinhvien a : dssv) {
                if (gettxtTimKiem().getText().trim().equalsIgnoreCase(a.getMaSV())) {
                    dstim.add(a);
                }
            }
            tableTim.setModel(new TableSV(dstim));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(QLySinhVien.this, e.toString(), "Error:", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void cbxNganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNganhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNganhActionPerformed

    private void cbxCoSoTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCoSoTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCoSoTTActionPerformed

    private void trangchuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trangchuMouseClicked
        // TODO add your handling code here:
        new Admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_trangchuMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        
        txtMaSV.setText("");
        txtTen.setText("");
        cbxNganh.setSelectedItem(0);
        txtGiaoVienHD.setText("");
        cbxCoSoTT.setSelectedItem(0);
        txtTrangThai.setText("");
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new QLySinhVien().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatLai;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatFile;
    private javax.swing.JComboBox<String> cbxCoSoTT;
    private javax.swing.JComboBox<String> cbxNganh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tableTim;
    private javax.swing.JTable tblSinhVien;
    private javax.swing.JMenu trangchu;
    private javax.swing.JTextField txtGiaoVienHD;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTrangThai;
    // End of variables declaration//GEN-END:variables
}
